name: sachinjot
favicon: null
layout_spectrum: 0.84868
typography_spectrum: 0.59745
title: SachinJot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20283e'
    - '#6d5b6d'
    - '#c1a8a4'
    - '#f1efef'
    - '#baad29'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
