name: sachinjot
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050304'
    - '#2d2824'
    - '#ae9c7e'
    - '#8d7a5f'
    - '#e8d1c8'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
