name: sachinjot
favicon: null
layout_spectrum: 0.75806
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050304'
    - '#2d2824'
    - '#ae9c7e'
    - '#8d7a5f'
    - '#e8d1c8'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 1
purpose: []
